# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Memory-Game' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Memory-Game

  target 'Memory-GameTests' do
    inherit! :search_paths
    pod 'Nimble'
    pod 'Quick'
  end

  target 'Memory-GameUITests' do
    # Pods for testing
  end

end
